Web/config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get '*path' => redirect { |_, request|
    "https://#{request.host_with_port.sub(/^www\./, '')}#{request.fullpath}" },
      constraints: lambda { |request| request.subdomain =~ /^www\./i }

  #root to: redirect { |_, request| PairconConfig.root_domain },
  #     constraints: lambda { |request|
  #       request.subdomain =~ /^www$/i && request.query_parameters.blank?
  #     }

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout'}, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :dashboard
    end

    unauthenticated do
      root 'users/sessions#new'
    end

    get '/recover', to: 'devise/passwords#new'
    post 'user_session', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'

  end

  match '/404', :to => 'errors#not_found', :via => :all
  match '/403', :to => 'errors#unauthorized_access', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all

  mount PdfjsViewer::Rails::Engine => "/pdf", as: 'pdf'

  resources :posts do
    member do
      get :delete
    end
  end

  resources :schedules do
    collection do
      get :get_sessions
      get :get_resources
      get :get_events
      get :get_events_user
      get :delete_resource
      get :new_resource
      get :new_event
      get :delete_event
      get :edit_event

      post :create_resource
      post :create_event
      post :create_resource
      post :create_event
      post :update_event

      delete :destroy_event
      delete :destroy_resource
    end
  end

  resources :papers do
    member do
     get :delete
     delete :destroy
    end
  end

  resources :conferences do
    member do
      get :bulk_upload
      get :invite
      get :delete
      get :user_recommendations

      post :create_invites
      post :destroy_cover
      post :destroy_logo
      post :save_cover
      post :save_logo
      post :attend_conference
      post :process_bulk_upload

      get :home
      get :about_panel
      get :recommendations
      get :posts
      get :schedule
      get :papers
    end
  end

  resources :notifications do
    collection do
      post :read_notification
    end
  end

  resources :home, path: '' do
    collection do
      get :terms
      get :privacy_policy
      get :search
    end
  end

  resources :users, except: [:index] do
    member do
      get :delete
      get :change_active_status
      get :password_reset
      get :timezone
      get :become_organizer
      get :refresh_profile
      get :approved_organizers
      get :pending_organizers
      get :publications

      delete :delete_account

      post :update_email_password
      post :save_logo
      post :destroy_logo
      post :submit_url
      post :request_organizer
      post :approve_organizer
      post :refresh_profile
    end

    collection do
      get :validation
    end
  end

  get '/user/:action/(:id)', controller: 'users'
  get '/auth/failure' => 'application#auth_failure', as: :auth_failure
  get '*path' => 'application#not_found', as: :not_found

end

Web/app/views/layouts/_flash_message.erb
<% init_error_flash %>

<div class="custom-flash-info alert alert-fixed alert-info alert-dismissable" id="notification_msg_box"
     style="display: none">

  <button class="close" type="submit" style="position: static; opacity: 1; font-size: 14px;">
    <i class="fa fa-times fa-fw paircon-custom"></i></button>
  <i class="fa fa-check fa-fw paircon-custom"></i>
  <span class="paircon-custom" id="flash_notice_message"><%= raw flash[:notice] %></span>
</div>

<div class="custom-flash-info alert alert-fixed alert-info alert-dismissable" id="processing_msg_box"
     style="display: none">

  <button class="close" type="submit" style="position: static; opacity: 1; font-size: 14px;">
    <i class="fa fa-times fa-fw paircon-custom"></i></button>
  <i class="fa fa fa-circle-o-notch fa-spin fa-fw paircon-custom"></i>
  <span class="paircon-custom"><%= 'We are currently processing your request. Please wait ...' %></span>
</div>

<div class="custom-flash-error alert alert-fixed alert-danger" id="error_message_box"
     style="display: none">
  <button type="submit" class="close" style="position: static; opacity: 1; font-size: 14px;">
    <i class="fa fa-times fa-fw"></i></button>
  <i class="fa fa-info"></i> <span id="flash_alert_message"><%= raw flash[:alert] %></span>
</div>

<script>
    setAutoHideFlashMsg('processing_msg_box');
    setAutoHideFlashMsg('notification_msg_box');
    setAutoHideFlashMsg('error_message_box');

    $('#notification_msg_box').css('display', '<%= flash[:notice].blank? ? 'none' : 'block' %>');
    $('#processing_msg_box').css('display', '<%= flash[:processing].blank? ? 'none' : 'block' %>');
    $('#error_message_box').css('display', '<%= flash[:alert].blank? ? 'none' : 'block' %>');
</script>

<% flash[:notice] = nil %>
<% flash[:alert] = nil %>
<% flash[:processing] = nil %>

Web/app/views/layouts/_flash_message.html.erb
<% init_error_flash %>

<div class="custom-flash-info alert alert-fixed alert-info alert-dismissable" id="notification_msg_box"
     style="display: none">

  <button class="close" type="submit" style="position: static; opacity: 1; font-size: 14px;">
    <i class="fa fa-times fa-fw cloudmerge-green"></i></button>
  <i class="fa fa-check fa-fw cloudmerge-green"></i>
  <span class="cloudmerge-green" id="flash_notice_message"><%= raw flash[:notice] %></span>
</div>

<div class="custom-flash-info alert alert-fixed alert-info alert-dismissable" id="processing_msg_box"
     style="display: none">

  <button class="close" type="submit" style="position: static; opacity: 1; font-size: 14px;">
    <i class="fa fa-times fa-fw cloudmerge-green"></i></button>
  <i class="fa fa fa-circle-o-notch fa-spin fa-fw cloudmerge-green"></i>
  <span class="cloudmerge-green"><%= 'We are currently processing your request. Please wait ...' %></span>
</div>

<div class="custom-flash-error alert alert-fixed alert-danger" id="error_message_box"
     style="display: none">
  <button type="submit" class="close" style="position: static; opacity: 1; font-size: 14px;">
    <i class="fa fa-times fa-fw"></i></button>
  <i class="fa fa-info"></i> <span id="flash_alert_message"><%= raw flash[:alert] %></span>
</div>

<script>
    setAutoHideFlashMsg('processing_msg_box');
    setAutoHideFlashMsg('notification_msg_box');
    setAutoHideFlashMsg('error_message_box');

    $('#notification_msg_box').css('display', '<%= flash[:notice].blank? ? 'none' : 'block' %>');
    $('#processing_msg_box').css('display', '<%= flash[:processing].blank? ? 'none' : 'block' %>');
    $('#error_message_box').css('display', '<%= flash[:alert].blank? ? 'none' : 'block' %>');
</script>

<% flash[:notice] = nil %>
<% flash[:alert] = nil %>
<% flash[:processing] = nil %>

Web/app/views/layouts/application.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/application/header' %>

<body class="nav-md">
<div class="container body" tabindex="0">
  <div class="main_container">
    <%= render 'layouts/application/application_top_nav' %>
    <%= render 'layouts/application/left_bar' %>
    <%= render 'layouts/application/modal', id: 'modal' %>

    <div class="right_col" role="main">
      <%= render 'layouts/application/flash_message' %>
      <div data-pjax-container>
        <%= yield %>
      </div>
    </div>
  </div>
</div>

</body>
<%= javascript_tag 'initializeApplication()' %>
<%= javascript_tag 'loadApplicationLayout()' %>
</html>

Web/app/views/layouts/home.erb
<!DOCTYPE html>
<html>
<% @page_title = 'Home' %>
<%= render 'layouts/home/header' %>

<body>
  <div class="loader"></div>
    <%= render 'layouts/home/welcome' %>
    <%= render 'layouts/home/statistics' %>
    <%= render 'layouts/home/features' %>
    <%= render 'layouts/home/landing' %>
    <%= render 'layouts/home/signup_banner' %>
    <%= render 'layouts/home/footer' %>
  </div>
</body>
<%= javascript_tag 'initializeApplication()' %>

<script>
    if (("onhashchange" in window)) {
        //modern browsers
        $(window).bind('hashchange', function () {
            window.location.hash = ''
        });

    }
</script>
</html>

Web/app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="x-pjax-version" content="v123">
  <title><%= @page_title %> - PairCon</title>

  <%= favicon_link_tag 'favicon.ico' %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="description" content="CloudMerge">
  <meta name="author" content="CloudMerge">
  <META Http-Equiv="Cache-Control" Content="no-cache"/>
  <META Http-Equiv="Pragma" Content="no-cache"/>
  <META Http-Equiv="Expires" Content="0"/>

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
<div class="container nopadding" id="main-container" >
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <%= link_to 'Home', root_path, class: 'skip-pjax' %>
      <%= link_to 'About', about_home_index_path, class: 'skip-pjax' %>
      <%= link_to 'Features', features_home_index_path, class: 'skip-pjax' %>
      <%= link_to 'Privacy Policy', privacy_policy_home_index_path, class: 'skip-pjax' %>
      <%= link_to 'Terms and Conditions', terms_home_index_path, class: 'skip-pjax' %>
      <% init_error_flash_for_login %>
      <div class="custom-flash-info alert alert-fixed alert-info alert-dismissable" id="error_callout"
           style="opacity: <%= flash[:alert].blank? ? '0' : '1' %>;">

        <button class="close" type="submit" style="position: static; opacity: 1; font-size: 14px;">
          <i class="fa fa-times fa-fw paircon-custom"></i></button>
        <i class="fa fa-info fa-fw paircon-custom"></i>
        <span class="paircon-custom"><%= raw flash[:alert] %></span>
      </div>

      <% flash[:alert] = nil %>
    </div>
  </div>
  <div class="row row-vertical-align main-content-login">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="row front-text-middle-align">
          <div class="signin_verticalcenter">
            <div data-pjax-container id="loginbox" >
              <%= yield %>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>

</body>

<%= javascript_tag 'enablePJAX()' %>

</html>

Web/app/views/layouts/public.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/application/header' %>

<body>
<div class="container body">
  <div class="main_container">
    <%= render 'layouts/public/top_nav' %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1 col-xs-12 col-sm-12">
        <%= render 'layouts/application/modal', id: 'modal' %>

        <div class="right_col" role="main" style="padding: 0px 20px;">
          <%= render 'layouts/application/flash_message' %>
          <div data-pjax-container>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
<%= javascript_tag 'initializeApplication()' %>
<%= javascript_tag 'loadApplicationLayout()' %>
</html>

Web/app/views/layouts/sign_up.erb
<!DOCTYPE html>
<html>
<% @page_title = 'Sign Up' %>
<%= render 'layouts/application/header' %>

<body class="nav-md footer_fixed">

<%= render 'layouts/application/signup_top_nav' %>
<div class="container body footer_fixed signup_container">
  <div class="main_container">

    <div id="main-form" class="form-group">
      <div class="col-md-10 col-sm-12 col-xs-12 col-md-offset-1 full-height">
        <div class="x_panel" style="background: #f7f7f7 !important;">
          <div class="x_content">

            <div id="wizard" class="form_wizard wizard_horizontal display-flex-column full-height">
              <ul class="wizard_steps anchor">
                <li class="flex-grow">
                  <a href="#step-1" class="selected" isdone="1" rel="1">
                    <span class="step_no">1</span>
                    <span class="step_descr">Welcome To Paircon<br></span>
                  </a>
                </li>
                <li class="flex-grow">
                  <a href="#step-2" class="selected" isdone="0" rel="2">
                    <span class="step_no">2</span>
                    <span class="step_descr">Personal Information<br></span>
                  </a>
                </li>
                <li class="flex-grow">
                  <a href="#step-3" class="disabled" isdone="0" rel="3">
                    <span class="step_no">3</span>
                    <span class="step_descr">Profile Picture<br></span>
                  </a>
                </li>
              </ul>
              <div class="stepContainer full-height">
                <div id="step-1" class="content full-height display-flex-column" style="display: none;">
                  <div class="flex-autoresize-middle flex-y-scroll user_registration_buffer">
                    <div class="row">
                      <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                        <h1 class="text-center">Welcome To Paircon!</h1>
                        <h3 class="text-center">Thanks for signing up! We'll guide you through your user
                          profile set-up so that you can get started. </h3>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                        <%= image_tag 'people.png', style: 'height: 500px; margin-top: 20px;' %>
                      </div>
                    </div>
                  </div>
                </div>
                <div id="step-2" class="content full-height display-flex-column" style="display: none;">
                  <%= form_for(@user, html: {id: 'new_user_registration', class: 'user_registration_form flex-autoresize-middle flex-y-scroll', multipart: true}) do |f| %>
                      <%= hidden_field_tag :referer, params[:referer] %>
                      <h1 class="text-center">Personal Information</h1>
                      <h3 class="text-center">Fields marked with <span class="required">*</span> are required.</h3>
                      <div class="row signup-row" id="user_form_row">
                        <div class="col-md-8 col-sm-8 col-xs-12 col-md-offset-2 col-sm-offset-2">
                          <div style="margin-top: 0px;" class="signin_verticalcenter">
                            <h3 class="input-label">Name <span class="required">*</span></h3>

                            <div class="row">
                              <div class="col-md-6 col-sm-6 col-xs-12">
                                <%= f.text_field :first_name, placeholder: 'First Name',
                                                 class: 'form-control form-signup-control', id: 'first_name' %>
                              </div>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                                <%= f.text_field :last_name, placeholder: 'Last Name',
                                                 class: 'form-control form-signup-control', id: 'last_name' %>
                              </div>
                            </div>

                            <h3 class="input-label signup-input-label">Email Address <span class="required">*</span>
                            </h3>
                            <div class="row">
                              <div class="col-md-12 col-sm-12 col-xs-12">
                                <%= f.text_field :email, placeholder: 'Email Address',
                                                 :class => 'form-control form-signup-control', disabled: 'disabled', style: 'opacity: 0.5' %>
                              </div>
                            </div>

                            <% unless Identity.find_by_user_id(current_user.id).nil? %>
                                <h3 class="input-label signup-input-label">Password <span class="required">*</span></h3>
                                <div class="row">
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                    <%= f.password_field :password, :autocomplete => 'true', :class => 'form-control', placeholder: "Password" %>
                                  </div>
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                    <%= f.password_field :password_confirmation, :autocomplete => 'true', :class => 'form-control', placeholder: "Confirm Password" %>
                                  </div>
                                </div>
                            <% end %>

                            <h3 class="input-label signup-input-label">Gender <span class="required">*</span></h3>
                            <div class="row">
                              <div class="col-md-12 col-sm-12 col-xs-12">
                                <%= f.select :gender, [['Male', 1], ['Female', 0]], {}, :class => 'form-control form-signup-control' %>
                              </div>
                            </div>

                            <h3 class="input-label signup-input-label">Academic Profile</h3>
                            <p class="input-label">Link your academic profile page with publications
                              listed. We'll use this list of publications to compute personalized recommendations.</p>
                            <div class="row">
                              <div class="col-md-12 col-sm-12 col-xs-12">
                                <%= f.text_field :url, :id => 'url', placeholder: 'URL', :class => 'form-control form-signup-control' %>
                              </div>
                            </div>

                            <h3 class="input-label signup-input-label">Phone Number</h3>
                            <div class="row">
                              <div class="col-md-12 col-sm-12 col-xs-12">
                                <%= f.text_field :phone_number, :id => 'phoneNumber', placeholder: 'Phone Number', :class => 'form-control form-signup-control' %>
                              </div>
                            </div>

                            <h3 class="input-label signup-input-label">Organization</h3>
                            <div class="row">
                              <div class="col-md-12 col-sm-12 col-xs-12">
                                <%= f.text_field :organization, :id => 'userOrganization', placeholder: 'Organization', :class => 'form-control form-signup-control' %>
                              </div>
                            </div>

                            <h3 class="input-label signup-input-label">Industry</h3>
                            <div class="row">
                              <div class="col-md-12 col-sm-12 col-xs-12">
                                <%= f.text_field :industry, :id => 'userIndustry', placeholder: 'Industry', :class => 'form-control form-signup-control' %>
                              </div>
                            </div>

                            <h3 class="input-label signup-input-label">Graduation Year</h3>
                            <div class="row">
                              <div class="col-md-12 col-sm-12 col-xs-12">
                                <%= f.select :grad_year, ((Time.zone.now.year - 150)..(Time.zone.now.year + 1)).to_a.reverse, {}, :id => 'userGradYear', placeholder: 'Graduation Year', :class => 'form-control form-signup-control', value: '' %>
                              </div>
                            </div>

                          </div>
                        </div>
                      </div>
                      </div>
                      <div id="step-3" class="content full-height display-flex-column" style="display: none;">
                        <div class="flex-autoresize-middle flex-y-scroll user_registration_buffer">
                          <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                              <h1 class="text-center">Profile Picture</h1>
                              <h3 class="text-center">Upload a profile picture and accept our
                                <strong><a href="<%= terms_home_index_url %>" target="_blank">Terms of Use
                                </a></strong> and
                                <strong><a href="<%= privacy_policy_home_index_url %>" target="_blank">
                                  Privacy Policy</a></strong>.</h3>
                            </div>
                          </div>
                          <div class="row" style="margin-top:20px;">
                            <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                              <div class="profile-image dropzone logo-image" data-resize="false" data-width="300" data-height="300"
                                   data-url="<%= save_logo_user_url(current_user) %>" data-image="<%= asset_path(current_user.profile_photo) %>"
                                   data-removeurl="<%= destroy_logo_user_url(current_user) %>">
                                <input class="invisible" id="profile-image-upload" type="file" name="thumb" accept="image/*"/>
                              </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                              <button id="upload_image_btn"
                                      class="btn btn-paircon btn-label btn-profile btn-padding" style="margin-top:20px;">
                                <i class="fa fa-upload"></i> Upload Image
                              </button>
                            </div>
                          </div>

                          <div class="row" style="margin-top: 50px;">
                            <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                              <input type="checkbox" class="checkbox-center" id="termsConditionCheckbox">
                              &ensp;&ensp;I have <strong>Read</strong> and <strong>Agree</strong> to Paircon's
                              <strong><a href="<%= terms_home_index_url %>" target="_blank">Terms of
                                Use</a></strong>
                              and
                              <strong><a href="<%= privacy_policy_home_index_url %>" target="_blank">Privacy
                                Policy</a></strong>.
                            </div>
                          </div>
                        </div>
                      </div>
                  <% end %>
                  </div>
            </div>
          </div>

          <div class="row" id="finalstep" style="display: none;">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div style="margin-top: 50px;">
                <h1 class="text-center">Please wait while we set up your Paircon account</h1>
                <div class="cssload-thecube" style="margin-top: 30px;">
                  <div class="cssload-cube cssload-c1"></div>
                  <div class="cssload-cube cssload-c2"></div>
                  <div class="cssload-cube cssload-c4"></div>
                  <div class="cssload-cube cssload-c3"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<%= render 'layouts/application/footer' %>

<%= javascript_tag 'initSignup()' %>

</body>
</html>