Web/config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get '*path' => redirect { |_, request|
    "https://#{request.host_with_port.sub(/^www\./, '')}#{request.fullpath}" },
      constraints: lambda { |request| request.subdomain =~ /^www\./i }

  #root to: redirect { |_, request| PairconConfig.root_domain },
  #     constraints: lambda { |request|
  #       request.subdomain =~ /^www$/i && request.query_parameters.blank?
  #     }

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout'}, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :dashboard
    end

    unauthenticated do
      root 'users/sessions#new'
    end

    get '/recover', to: 'devise/passwords#new'
    post 'user_session', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'

  end

  match '/404', :to => 'errors#not_found', :via => :all
  match '/403', :to => 'errors#unauthorized_access', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all

  mount PdfjsViewer::Rails::Engine => "/pdf", as: 'pdf'

  resources :posts do
    member do
      get :delete
    end
  end

  resources :schedules do
    collection do
      get :get_sessions
      get :get_resources
      get :get_events
      get :get_events_user
      get :delete_resource
      get :new_resource
      get :new_event
      get :delete_event
      get :edit_event

      post :create_resource
      post :create_event
      post :create_resource
      post :create_event
      post :update_event

      delete :destroy_event
      delete :destroy_resource
    end
  end

  resources :papers do
    member do
     get :delete
     delete :destroy
    end
  end

  resources :conferences do
    member do
      get :bulk_upload
      get :invite
      get :delete
      get :user_recommendations

      post :create_invites
      post :destroy_cover
      post :destroy_logo
      post :save_cover
      post :save_logo
      post :attend_conference
      post :process_bulk_upload

      get :home
      get :about_panel
      get :recommendations
      get :posts
      get :schedule
      get :papers
    end
  end

  resources :notifications do
    collection do
      post :read_notification
    end
  end

  resources :home, path: '' do
    collection do
      get :terms
      get :privacy_policy
      get :search
    end
  end

  resources :users, except: [:index] do
    member do
      get :delete
      get :change_active_status
      get :password_reset
      get :timezone
      get :become_organizer
      get :refresh_profile
      get :approved_organizers
      get :pending_organizers
      get :publications

      delete :delete_account

      post :update_email_password
      post :save_logo
      post :destroy_logo
      post :submit_url
      post :request_organizer
      post :approve_organizer
      post :refresh_profile
    end

    collection do
      get :validation
    end
  end

  get '/user/:action/(:id)', controller: 'users'
  get '/auth/failure' => 'application#auth_failure', as: :auth_failure
  get '*path' => 'application#not_found', as: :not_found

end

Web/app/controllers/application_controller.rb
# Controller primarily responsible for handling Application Wide Information
class ApplicationController < ActionController::Base
  include UrlHelper
  include ActiveDevice

  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found
  layout :layout_by_resource, except: [:about, :features]

  helper_method :current_page, :log
  helper :all

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :is_app_init_for_sign_up
  before_action :set_mailer_url_options
  before_action :set_cache_buster
  before_action :load_left_column
  skip_before_action :set_mobile_format

  etag { current_user.try :user_id }

  # Action used to destroy cache
  # @return [None]
  def set_cache_buster
    response.headers['Cache-Control'] = 'no-cache, no-store, max-age=0, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] =' "Fri, 01 Jan 1990 00:00:00 GMT"'
  end

  # Action used to run rails logger debug
  # @param data [String] Message that needs to be shown in Log
  # @return [None]
  def log(data)
    Rails.logger.debug("\n\n==========LOG============\n\n#{data}\n\n=======================\n\n")
  end

  # Action used to configure sign up parameters
  # @return [None]
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({roles: []}, :email, :password, :password_confirmation, :first_name, :last_name) }
  end

  # Action executed if something is not found
  # @return [HTML] Renders Internal Server Error
  def not_found
    render file: '/errors/internal_server_error', formats: [:html], status: 404, layout: user_signed_in? ? 'application' : 'error'
  end

  # Action used to define the type of resource (different themes)
  # @return [None]
  def layout_by_resource
    unless request.headers['X-PJAX']

      if request.xhr?
        false
      else
        if devise_controller?
          if resource_name == :user
            'home'
          end
        elsif request.path =~ /\/oauth2/i
          'home'
        else
          'application'
        end
      end
    else
      response.headers['X-PJAX-Version'] = 'v123'
      false
    end
  end

  private

  # Method used to load left column in application layout
  # @return [None]
  def load_left_column
    if signed_in?(:user)
      @attending_conferences = Conference.my_attending_conferences(current_user)

      unless current_user.attendee?
        @organizing_conferences = Conference.my_organizing_conferences(current_user)
      end

    end
  end

  # Method used to check the type of layout
  # @return [String] Returns Layout Name
  def layout
    request.xhr? ? false : 'application'
  end

  # Method used to check current page
  # @return [String] Returns Controller_ActionName as String
  def current_page
    "#{params[:controller]}_#{params[:action]}"
  end

  # Method used to set user locale
  # @return [None]
  def set_locale
    if !params[:lang].blank?
      I18n.locale = params[:lang]
    elsif !current_user.nil?
      I18n.locale = current_user.default_lang
    else
      I18n.locale = 'en'
    end
  end

  # Method used to set current timezone
  # @return [None]
  def set_timezone
    if !signed_in?(:user)
      Time.zone = find_timezone()
    elsif !current_user.time_zone_name.nil?
      Time.zone = ActiveSupport::TimeZone[current_user.time_zone_name]
    end
  end

  # Method used to find the current timezone of the user
  # @return [TimeZone] Returns Timezone
  def find_timezone
    time_zone = ActiveSupport::TimeZone[cookies[:time_zone_name]] unless cookies[:time_zone_name].blank?

    if time_zone.nil?
      unless cookies[:gmt_offset_minutes].blank?
        gmt_offset_seconds = cookies[:gmt_offset_minutes].to_i.minutes
        time_zone = ActiveSupport::TimeZone[gmt_offset_seconds]
      end

      time_zone = ActiveSupport::TimeZone['UTC'] if time_zone.nil?
      cookies[:time_zone_name] = time_zone.name
    end

    time_zone
  end

  # Method used to update the timezone
  # @return [None]
  def save_timezone!
    timezone = find_timezone()
    current_user.time_zone_name = timezone.name
    current_user.save!(validate: false)
  end

  # Method to overwrite the sign_in redirect path method
  # @return [None]
  def after_sign_in_path_for(resource_or_scope)
    save_timezone!() if current_user.time_zone_name.blank?
    stored_location_for(resource_or_scope) || dashboard_path()
  end

  # Method to overwrite the sign_out redirect path method
  # @return [None]
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_url()
  end

  # Method executed on sign up
  # @return [None]
  def is_app_init_for_sign_up
    ActiveRecord::Base.skip_callbacks = false

    # session[:backlink] = nil if params[:action] != "files" && params[:action] != "update_flags"

    if current_user && !current_user.is_app_init && !devise_controller? &&
        params[:action] != 'save_logo' && params[:action] != 'destroy_logo' && params[:action] != 'validation'

      if current_page == 'users_edit' || current_page == 'users_update'
        params[:referer] = REFERERS[:app_init]
      else
        redirect_to edit_user_path(id: current_user, referer: REFERERS[:app_init]) and return
      end
    end
  end

  # Method used to set mailer
  # @return [None]
  def set_mailer_url_options
    ActionMailer::Base.default_url_options[:host] = with_subdomain(request.subdomain)
  end

end

Web/app/helpers/application_helper.rb
# Helper primarily responsible for providing application wide Utils
module ApplicationHelper
  include NotificationsHelper

  # Creates a Page Title With <H1>
  # @param title [String] String to create a Tag for
  # @return [HTML] H1 Tag with Page Title
  def page_title(title)
    @page_title = title
    content_tag(:h1, @page_title, class: ['font-light'])
  end

  # Creates a Page Title for Browser
  # @param title [String] String to create a Tag for
  # @return [HTML] Set Title Tag
  def header_title(title)
    @page_title = title
    content_tag(:title, @page_title + ' - Paircon')
  end

  # Creates a jS Setting for Locale
  # @return [HTML] Javascript Tag
  def locale_setting_js
    javascript_tag("I18n.defaultLocale='#{I18n.default_locale}';I18n.locale='#{I18n.locale}';")
  end

  # Creates a jS Setting for Time zone
  # @return [HTML] Javascript Tag
  def time_zone_setting_js
    javascript_tag('$(function(){try{document.cookie="time_zone_name="+getTimezoneName();document.cookie="gmt_offset_minutes="+ -1*(new Date).getTimezoneOffset();}catch(e){}});')
  end

  # Creates a Font Awesome icon with text
  # @param icon_name [String] Name of the Font Awesome Icon
  # @param text [String] Required String
  # @return [HTML] Returns HTML with Icon and Text
  def icon_text(icon_name, text = '')
    content_tag(:i, nil, :class => "fa fa-fw fa-#{icon_name.to_s}") + " " + content_tag(:span, text.html_safe)
  end

  # Creates a Link That opens a Modal
  # @param name [String] The name for the link
  # @param link_to_remote_options [Hash] Any Remote Options for Modal
  # @param html_options [Hash] Any HTML Options
  # @return [HTML] Returns Link for opening Modal
  def link_to_modal(name, link_to_remote_options = {}, html_options = {})
    html_options.merge!({data: {toggle: 'modal', target: '#modal', backdrop: 'static'}})
    link_to(name, link_to_remote_options, html_options)
  end

  # Initializes error flash on login
  # @return [HTML] Returns Flash Message
  def init_error_flash_for_login()
    flash_errors = [flash[:error], flash[:alert], flash[:notice]]
    flash_errors = flash_errors + resource.errors.full_messages if defined? resource
    flash_errors.compact!
    flash[:alert] = flash_errors.join('<br />') unless flash_errors.blank?
  end

  # Initializes error flash after logging in
  # @return [HTML] Returns Flash Message
  def init_error_flash()
    flash_errors = [flash[:error], flash[:alert]]
    flash_errors = flash_errors + resource.errors.full_messages if defined? resource
    flash_errors.compact!
    flash[:alert] = flash_errors.join('<br />') unless flash_errors.blank?
  end

end

Web/app/views/layouts/application/_application_top_nav.erb
<% head_btn_class = 'pull-left header-button btn btn-toolbar btn-default header_btns header-font-small ' %>

<div class="top_nav">
  <div class="nav_menu display-flex" style="margin-bottom: 0px; width: 100%;">
    <nav class="flex-grow">
      <div class="nav navbar-paircon">
        <!-- Toggle menu -->
        <div class="nav toggle" style="margin-top: -5px;">
          <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        <!-- Add new conference -->
        <div>
          &nbsp;<%= link_to_modal icon_text('plus-circle', 'Create Conference'), new_conference_path(), class: head_btn_class %>
        </div>
        <div class="hidden-xs search-top">
          <%= render 'layouts/application/search' %>
        </div>

        <!-- User dropdown -->
        <ul id="user-dropdown" class="nav navbar-nav navbar-right pull-right navbar-user">
          <li>
            <a href="#" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              <img src="<%= asset_path(current_user.profile_photo) %>" id="userimage" alt=""><span id="username"><%= current_user.full_name %></span>
              <i class="fa fa-angle-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
              <li>
                <% if current_user.attendee? and !current_user.pending_organizer %>
                    <a data-toggle="modal" data-target="#modal" data-backdrop="static" href="<%= become_organizer_user_path(current_user.id) %>">Become
                      an Organizer
                      <i class="pull-right fa fa-users dropdown-user-icons"></i>
                    </a>
                <% elsif current_user.attendee? and current_user.pending_organizer %>
                    <a href="#" class="disabled">Your Organizer Request is Pending</a>
                <% end %>
              </li>
              <li><a href="<%= user_path(current_user) %>">Settings
                <i class="pull-right fa fa-cog dropdown-user-icons"></i>
              </a></li>
              <li><a href="<%= PairconConfig::url[:support] %>" target="_blank">Feedback
                <i class="pull-right fa fa-comments dropdown-user-icons"></i></a>
              </li>
              <li><a href="<%= PairconConfig::url[:help] %>" target="_blank">Help
                <i class="pull-right fa fa-question-circle dropdown-user-icons"></i></a>
              </li>
              <li class="divider"></li>
              <li>
                <a id="logout_link" rel="nofollow" data-method="delete" href="<%= destroy_user_session_url(:protocol => "#{Rails.env.production? ? 'https://' : 'http://'}") %>">Logout
                  <i class="fa fa-sign-out pull-right dropdown-user-icons"></i></a>
              </li>
            </ul>
          </li>
          <!-- For User Notifications -->
          <li class="dropdown" tabindex="5006" id="notification_panel"></li>

          <!-- For User Publications -->
          <li><%#= link_to icon_text('user', ''), publications_user_path(current_user) %></li>
        </ul>
      </div>
    </nav>
  </div>
</div>

<% if current_user.attendee? %>
    <script>$('.header_btns').hide();</script>
<% end %>

Web/app/views/layouts/application/_flash_message.erb
<% init_error_flash %>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom: -55px; z-index: 100;">
    <div class="custom-flash-info alert alert-fixed alert-info alert-dismissable" id="notification_msg_box"
         style="display: none">

      <button id="notification_msg_box_close" class="close" type="submit" style="position: static; opacity: 1; font-size: 14px;">
        <i class="fa fa-times fa-fw paircon-custom"></i></button>
      <i class="fa fa-check fa-fw paircon-custom"></i>
      <span class="paircon-custom" id="flash_notice_message"><%= raw flash[:notice] %></span>
    </div>

    <div class="custom-flash-info alert alert-fixed alert-info alert-dismissable" id="processing_msg_box"
         style="display: none">

      <button id="processing_msg_box_close" class="close" type="submit" style="position: static; opacity: 1; font-size: 14px;">
        <i class="fa fa-times fa-fw paircon-custom"></i></button>
      <i class="fa fa fa-circle-o-notch fa-spin fa-fw paircon-custom"></i>
      <span class="paircon-custom"><%= 'We are currently processing your request. Please wait ...' %></span>
    </div>

    <div class="custom-flash-error alert alert-fixed alert-danger" id="error_message_box"
         style="display: none">
      <button id="error_message_box_close" type="submit" class="close" style="position: static; opacity: 1; font-size: 14px;">
        <i class="fa fa-times fa-fw"></i></button>
      <i class="fa fa-info"></i> <span id="flash_alert_message"><%= raw flash[:alert] %></span>
    </div>
  </div>
</div>

<script>
    setAutoHideFlashMsg('processing_msg_box');
    setAutoHideFlashMsg('notification_msg_box');
    setAutoHideFlashMsg('error_message_box');

    $('#notification_msg_box').css('display', '<%= flash[:notice].blank? ? 'none' : 'block' %>');
    $('#processing_msg_box').css('display', '<%= flash[:processing].blank? ? 'none' : 'block' %>');
    $('#error_message_box').css('display', '<%= flash[:alert].blank? ? 'none' : 'block' %>');
</script>

<% flash[:notice] = nil %>
<% flash[:alert] = nil %>
<% flash[:processing] = nil %>

Web/app/views/layouts/application/_footer.erb
<footer class="footer">
  <div class="mid_center">
    Copyright © 2017 Paircon. All rights reserved.
  </div>
  <div class="clearfix"></div>
</footer>

Web/app/views/layouts/application/_header.erb
<head>
  <meta http-equiv="x-pjax-version" content="v123">
  <title><%= @page_title %> - Paircon</title>

  <%= favicon_link_tag 'favicon.ico' %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Paircon">
  <meta name="author" content="Paircon">
  <META Http-Equiv="Cache-Control" Content="no-cache"/>
  <META Http-Equiv="Pragma" Content="no-cache"/>
  <META Http-Equiv="Expires" Content="0"/>

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application-layout', media: 'all' %>
  <%= stylesheet_link_tag 'scheduler/calendar/fullcalendar.print.min', media: 'print' %>
  <%= stylesheet_link_tag 'scheduler/calendar/scheduler.min' %>


  <%= javascript_include_tag 'application-layout' %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=<%= PairconConfig.google_api_key %>" async defer></script>

  <%= locale_setting_js() %>
  <%= time_zone_setting_js() %>

</head>

Web/app/views/layouts/application/_left_bar.erb
<div class="col-md-3 left_col menu_fixed">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="<%= root_path() %>" class="site_title navbar-brand">
        <%= image_tag 'Top-Header-notext.png', alt: '', class: 'navbar-image', style: 'margin-left: 5px; height: 30px; display: inline-block;' %>
        <h2 style="color: #e6e7e8; display: inline;">PAIR<span class="logo-dec">CON</span></h2>
      </a>
    </div>

    <div class="clearfix"></div>

    <div class="profile clearfix">
      <div class="profile_pic">
        <img src="<%= asset_path(current_user.profile_photo) %>" alt="..." class="img-circle profile_img">
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2><%= truncate current_user.last_name, :length => 9, :separator => ' ' if current_user %></h2>
      </div>
    </div>

    <br/>

    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

      <div class="search visible-xs" id="search" style="margin-bottom: 20px;">
        <a href="javascript:"><i class="fa fa-search opacity-control"></i></a>

        <%= form_tag search_home_index_path, method: :get, data: {pjax: true} do %>
            <div class="form-group search-box">
              <input class="search-query" id="search_val" name="search_val" type="text"
                     value="<%= params[:search_val] %>" placeholder="Search Everywhere">
              <button id="app_search_btn" type="submit"><i class="fa fa-search"></i></button>
            </div>
        <% end %>

      </div>

      <div class="menu_section">
        <h3><b><u>DASHBOARD</u></b></h3>
        <ul class="nav side-menu">
          <li><%= link_to 'Home', root_path %></li>
        </ul>
      </div>

      <% if current_user.admin? %>
          <div class="menu_section">
            <h3><b><u>ADMIN</u></b></h3>
            <ul class="nav side-menu">
              <li><a href="<%= pending_organizers_user_path(current_user) %>">Pending Organizers</a></li>
              <li><a href="<%= approved_organizers_user_path(current_user) %>">Approved Organizers</a></li>
            </ul>
          </div>
      <% end %>

      <% i = 1 %>
      <% if @attending_conferences.length != 0 %>
          <div class="menu_section">
            <h3>
              <b><u>FOLLOWING<span class="pull-right"><%= link_to icon_text('plus-circle'), conferences_path(view: 'attendee'), class: 'light-grey-text', style: 'margin-right: 5px;' %></span>
              </u></b></h3>
            <ul class="nav side-menu">
              <% @attending_conferences[0..5].each do |conference| %>
                  <li class="overflow-ellipsis">
                    <a id="<%= "attending_conference_#{conference.id}" %>" href="<%= conference_path(conference) %>"><%= conference.get_name(i) %></a>
                  </li>
                  <% i = i + 1 %>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% unless current_user.attendee? %>
          <% if @organizing_conferences.length != 0 %>
              <div class="menu_section">
                <h3><b>
                  <u>ORGANIZING</u><span class="pull-right"><%= link_to icon_text('plus-circle'), conferences_path(view: 'organizer'), class: 'light-grey-text', style: 'margin-right: 5px;' %></span></b>
                </h3>
                <ul class="nav side-menu">
                  <% @organizing_conferences[0..5].each do |conference| %>
                      <li class="overflow-ellipsis">
                        <a id="<%= "organizing_conference_#{conference.id}" %>" href="<%= conference_path(conference) %>"><%= conference.get_name(i) %></a>
                      </li>
                      <% i = i + 1 %>
                  <% end %>
                </ul>
              </div>
          <% end %>
      <% end %>
    </div>


  </div>
</div>

<div class="sidebar-footer hidden-small text-center" style="margin-bottom: 10px;">
  <small>Copyright © 2017 Paircon. All rights reserved</small>
</div>

Web/app/views/layouts/application/_modal.html.erb
<% modal_size = defined?(size) ? "modal-#{size}" : '' %>

<div class="modal fade" id="<%= id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog <%= modal_size %>">
    <div class="modal-content" id="modal_content" style="padding: 10px 25px;">
    </div>
  </div>
</div>

Web/app/views/layouts/application/_no_result.erb
<div style="margin-top: 30px; font-style: italic; text-align: center;">
  <div><img style="opacity: 0.3; height: 50px;" src="<%= asset_path 'sad.png' %>"/></div>
  <div style="margin-top: 30px;">
    <%= body %>
  </div>
</div>

Web/app/views/layouts/application/_organizer_notif.erb
<div class="col-md-6">
  <div class="x_panel">
    <div class="x_title">
      <h2>Notifications from Organizer</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <ul class="list-unstyled msg_list">
        <li>
          <a>
            <span class="image">
              <img src="<%= asset_path 'Male.jpg' %>" alt="img">
            </span>
            <span>
              <span>John Smith</span>
              <span class="time">3 mins ago</span>
            </span>
            <span class="message">
              Film festivals used to be do-or-die moments for movie makers. They were where you met the producers that
            </span>
          </a>
        </li>
        <li>
          <a>
            <span class="image">
              <img src="<%= asset_path 'Male.jpg' %>" alt="img">
            </span>
            <span>
              <span>John Smith</span>
              <span class="time">3 mins ago</span>
            </span>
            <span class="message">
              Film festivals used to be do-or-die moments for movie makers. They were where you met the producers that
            </span>
          </a>
        </li>
        <li>
          <a>
            <span class="image">
              <img src="<%= asset_path 'Male.jpg' %>" alt="img">
            </span>
            <span>
              <span>John Smith</span>
              <span class="time">3 mins ago</span>
            </span>
            <span class="message">
              Film festivals used to be do-or-die moments for movie makers. They were where you met the producers that
            </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

Web/app/views/layouts/application/_search.erb
<%= form_tag search_home_index_path, method: :get, data: {pjax: true} do %>
  <div class="col-xs-12 pull-right top_search">
    <div class="input-group">
      <input class="form-control" id="search_val" name="search_val" value="<%= params[:search_val] %>" placeholder="Search for..." type="text">
      <span class="input-group-btn">
        <button id="app_search_btn" class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </div>
<% end %>

Web/app/views/layouts/application/_signup_top_nav.erb
<div class="top_nav sign_up_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav navbar-paircon">
        <%= image_tag 'Top-Header-notext.png', alt: '', class: 'navbar-image', style: is_mobile_browser? ? 'margin-left: 20px;' : '' %>
        <ul id="user-dropdown" class="navbar-user nav navbar-nav navbar-right pull-right" >
          <li class="">
            <a href="javascript:" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              <img src="<%= asset_path(current_user.profile_photo) %>" id="userimage" alt=""><span id="username"><%= current_user.full_name %></span>
              <span class=" fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
              <li class="username" style="background-color: transparent !important; padding-bottom: 10px;">
                <div>
                  <div style="margin-top: 7px; text-align: center;">
                    <span id="welcomeLastName">Welcome <%= truncate current_user.last_name, :length => 50, :separator => ' ' if current_user %>
                      !</span>
                  </div>
                </div>
              </li>
              <li><a href="<%= PairconConfig::url[:support] %>" target="_blank">Support
                <i class="pull-right fa fa-comments dropdown-user-icons"></i></a>
              </li>
              <li><a href="<%= PairconConfig::url[:help] %>" target="_blank">Help
                <i class="pull-right fa fa-question-circle dropdown-user-icons"></i></a>
              </li>
              <li class="divider"></li>
              <li>
                <a id="logout_link" rel="nofollow" data-method="delete" href="<%= destroy_user_session_url(:protocol => "#{Rails.env.production? ? 'https://' : 'http://'}") %>">Logout
                  <i class="fa fa-sign-out pull-right dropdown-user-icons"></i></a>
                </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</div>