Web/config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get '*path' => redirect { |_, request|
    "https://#{request.host_with_port.sub(/^www\./, '')}#{request.fullpath}" },
      constraints: lambda { |request| request.subdomain =~ /^www\./i }

  #root to: redirect { |_, request| PairconConfig.root_domain },
  #     constraints: lambda { |request|
  #       request.subdomain =~ /^www$/i && request.query_parameters.blank?
  #     }

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout'}, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :dashboard
    end

    unauthenticated do
      root 'users/sessions#new'
    end

    get '/recover', to: 'devise/passwords#new'
    post 'user_session', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'

  end

  match '/404', :to => 'errors#not_found', :via => :all
  match '/403', :to => 'errors#unauthorized_access', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all

  mount PdfjsViewer::Rails::Engine => "/pdf", as: 'pdf'

  resources :posts do
    member do
      get :delete
    end
  end

  resources :schedules do
    collection do
      get :get_sessions
      get :get_resources
      get :get_events
      get :get_events_user
      get :delete_resource
      get :new_resource
      get :new_event
      get :delete_event
      get :edit_event

      post :create_resource
      post :create_event
      post :create_resource
      post :create_event
      post :update_event

      delete :destroy_event
      delete :destroy_resource
    end
  end

  resources :papers do
    member do
     get :delete
     delete :destroy
    end
  end

  resources :conferences do
    member do
      get :bulk_upload
      get :invite
      get :delete
      get :user_recommendations

      post :create_invites
      post :destroy_cover
      post :destroy_logo
      post :save_cover
      post :save_logo
      post :attend_conference
      post :process_bulk_upload

      get :home
      get :about_panel
      get :recommendations
      get :posts
      get :schedule
      get :papers
    end
  end

  resources :notifications do
    collection do
      post :read_notification
    end
  end

  resources :home, path: '' do
    collection do
      get :terms
      get :privacy_policy
      get :search
    end
  end

  resources :users, except: [:index] do
    member do
      get :delete
      get :change_active_status
      get :password_reset
      get :timezone
      get :become_organizer
      get :refresh_profile
      get :approved_organizers
      get :pending_organizers
      get :publications

      delete :delete_account

      post :update_email_password
      post :save_logo
      post :destroy_logo
      post :submit_url
      post :request_organizer
      post :approve_organizer
      post :refresh_profile
    end

    collection do
      get :validation
    end
  end

  get '/user/:action/(:id)', controller: 'users'
  get '/auth/failure' => 'application#auth_failure', as: :auth_failure
  get '*path' => 'application#not_found', as: :not_found

end

Web/app/controllers/users/omniauth_callbacks_controller.rb
# This Controller is used to handle Social Media Authentication Callbacks
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # Function executed on successful callback
  # @param [Object] provider the name of provider
  # @return [HTML] Redirects New User Registration URL
  def self.provides_callback_for(provider)
    define_method provider do
      auth = env['omniauth.auth']
      @user = IdentifierService.new(auth, current_user).resolve

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = auth
        redirect_to new_user_registration_url
      end
    end
  end

  [:google_oauth2, :facebook].each { |provider| provides_callback_for provider }

  # Function executed on failure
  # @return [HTML] Redirects New User Session URL
  def failure
    flash[:error] = 'Unable to continue as access has been denied.'
    redirect_to new_user_session_path and return
  end

end

Web/app/controllers/users/registrations_controller.rb
# Controller handling Registrations From Devise (Extension)
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  # Function executed on being inactive
  # @return [HTML] Redirects to new user session url
  def after_inactive_sign_up_path_for(resource)
    new_user_session_url()
  end
end

Web/app/controllers/users/sessions_controller.rb
# Controller handling Sessions From Devise (Extension)
class Users::SessionsController < Devise::SessionsController
  # Default layout
  layout 'home'

  # Function handling making a new devise session
  # @return [HTML] Renders New View
  def new
    super
  end

  # Function handling successful creation of session
  # @return [HTML] Redirects to successful session creation root
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    if !session[:return_to].blank?
      redirect_to session[:return_to]
      session[:return_to] = nil
    else
      respond_with resource, :location => after_sign_in_path_for(resource)
    end
  end
end

Web/app/controllers/users_controller.rb
# Controller primarily responsible for handling Users
class UsersController < ApplicationController

  require 'base64'
  require 'scrapper/pdf_scrapper'
  require 'fileutils'

  before_action :check_session, :only => [:show]
  before_action :authenticate_user!, except: [:publication, :validation]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # Action used to show list of approved organizers
  # @return [HTML] Render Approved Organizers View
  def approved_organizers
    @user = current_user
    @approved_organizers = User.joins(:organizer).select(:user_id, :first_name, :last_name, :email, :industry, :organization, 'organizers.updated_at').where(organizers: {approved: true})
  end

  # Action used to show list of pending organizers
  # @return [HTML] Render Pending Organizers View
  def pending_organizers
    @user = current_user
    @pending_organizers = User.joins(:organizer).select(:user_id, :first_name, :last_name, :email, :industry, :organization, 'organizers.created_at').where(organizers: {approved: false})
  end

  # Action used to process the approval of an organizer
  # @return [HTML] Render Status as HTML
  def approve_organizer
    tran_success = false
    user = User.find(params[:id])
    Organizer.transaction do
      tran_success = user.update!(user_type: User.user_types[:organizer])
      tran_success = tran_success and (Organizer.find_by_user_id(params[:id]).update!(approved: true)) 

      unless tran_success
        raise ActiveRecord::Rollback
      end
    end

    if tran_success
      render status: :ok, text: "You Have Approved #{user.full_name} As An Organizer."
    else
      render status: :internal_server_error, text: "There was some problem while trying to approving #{user.full_name}. Please try again later ..."
    end
  end

  # Action used to process request of an organizer
  # @return [HTML] Redirect Back to Last Location
  def request_organizer
    @user = current_user
    @organizer = Organizer.create!(user_id: @user.id)

    if @organizer
      flash[:notice] = 'Your Have Requested Organizer Access, Please Wait For Your Request To Be Processed.'
    else
      flash[:error] = 'There was some error while trying to process your request. Please try again later.'
    end

    redirect_back(fallback_location: :back)
  end

  # Action used to open modal for request of becoming organizer
  # @return [HTML] Render Become Organizer Modal
  def become_organizer
    @user = current_user
  end

  # Action used to show settings for user
  # @return [HTML] Render Show View
  def show
  end

  # Action used to edit settings for organizer
  # @return [HTML] Render Edit View
  def edit
    render layout: 'sign_up' if params[:referer] == REFERERS[:app_init] && !current_user.is_app_init
  end

  # Action used to refresh publication profile for user
  # @return [JSON] Render Status as JSON
  def refresh_profile
    @user = current_user
    if not @user.url.blank?
      @user.scrape_profile
    end

    render json: {status: :ok, message: 'Please wait while we refresh your publications.' }
  end

  # Action used to display publications [Under Construction]
  # @return [HTML] Render Publications View
  def publications
    @user = User.find(params[:id])
  end

  # Action used to update user
  # @return [HTML] Redirect to previous location
  # @return [JSON] Render status as JSON
  def update
    respond_to do |format|
      scrape_profile = false
      if params[:referer] == REFERERS[:app_init]
        init_app_after_first_sign_up
        save_logo
        if(not @user.url.blank?)
          scrape_profile = true
        end
      end

      if @user.is_app_init and (not user_params[:url].blank?) and (user_params[:url] != @user.url)
        scrape_profile = true
      end

      if @user.update_attributes(user_params)
        if scrape_profile
          @user.scrape_profile
        end
        if params[:referer] == REFERERS[:app_init]
          unless Identity.find_by_user_id(@user.id).nil?
            sign_in @user, :bypass => true
          end
          format.html { redirect_to dashboard_path(), notice: "Hi #{@user.full_name.capitalize}! Welcome to Paircon ... Look at upcoming research conferences and get personalized recommendations today!" }
        else
          # @user.activity(:update)
          format.html { redirect_to @user, notice: 'Your personal information has been updated successfully.' }
          format.json { render :show, status: :ok, location: @user }
        end
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action used to delete user account
  # @return [HTML] Redirect to Login Page [Success] or to User Page [Failure]
  def delete_account
    @user = current_user
    if verify_recaptcha
      if @user.valid_password?(params[:user][:current_password])
        @user.destroy
        sign_out @user
        flash[:notice] = 'Your account has been successfully deleted from Paircon.'
        redirect_to new_user_session_url() and return
      else
        flash[:error] = 'Your current password appears to be incorrect. Please try again later ...'
        respond_to do |format|
          format.html { redirect_to user_path(User.find(params[:id])) }
        end
      end
    else
      flash[:error] = 'The Captcha entered appears to be incorrect. Please try again later ...'
      respond_to do |format|
        format.html { redirect_to user_path(User.find(params[:id])) }
      end
    end

  end

  # Action used to show modal for account deletion
  # @return [HTML] Render Delete Modal
  def delete
    @user = current_user
  end

  # Action used to update and save the logo
  # @return [JSON] Render Status as JSON
  def save_logo
    unless params[:name].blank?
      FileUtils.mkdir_p "#{Rails.root}/tmp/logo"
      new_file = "#{Rails.root}/tmp/logo/#{params[:name]}"

      File.open(new_file, 'wb') do |file|
        file.write(Base64.decode64 params[:data].split(",")[1])
      end

      current_user.logo = File.open(new_file, 'r')
      current_user.save!(validate: false)
      # current_user.activity(:update)

      File.delete(new_file)
    end

    render json: {status: :success, url: current_user.profile_photo, filename: current_user.logo_file_name} if params[:referer] != REFERERS[:app_init]
  end

  # Action used to destroy user
  def destroy
    @user.destroy
  end

  # Action used to destroy user logo
  # @return [JSON] Render Status as JSON
  def destroy_logo
    current_user.logo = nil unless current_user.logo.nil?
    current_user.save!(validate: false)
    render json: {status: :success}
  end

  # Action used show modal for user password reset
  # @return [HTML] Render Password Reset Modal
  def password_reset
    @user = current_user
  end

  # Action used to update email password
  # @return [HTML] Redirect to Last location [Success] or User Show View [Failure]
  def update_email_password

    @user = current_user

    if verify_recaptcha
      if @user.update_with_password(user_params)
        sign_in(@user, :bypass => true)

        if params[:user][:password].blank?
          flash[:notice] = 'Email Address has been updated succesfully.'
        else
          flash[:notice] = 'Password has been updated succesfully. '
        end

        redirect_to :back
      else
        flash[:error] = 'Your current password appears to be incorrect. Please try again later ...'
        respond_to do |format|
          format.html { redirect_to user_path(User.find(params[:id])) }
        end
      end
    else
      flash[:error] = 'The Captcha entered appears to be incorrect. Please try again later ...'
      respond_to do |format|
        format.html { redirect_to user_path(User.find(params[:id])) }
      end
    end
  end

  # Action used to validate user
  # @return [boolean] True or False based on the validation
  def validation
    if !params[:is_login].blank?
      render plain: current_user.nil? ? 'false' : 'true'
    elsif !params[:user][:username].blank?
      render plain: User.where(username: params[:user][:username]).first.nil? ? 'true' : 'false'
    elsif !params[:user][:email].blank?
      render plain: User.where(email: params[:user][:email]).first.nil? ? 'true' : 'false'
    else
      render plain: 'false'
    end
  end

  private

  # Method used to check if the user is logged in
  def check_session
    redirect_to root_path unless current_user
  end

  # Method used to set user
  def set_user
    @user = current_user
  end

  # Method used to permit user parameter attributes
  def user_params
    params.require(:user).permit!
  end

  # Method called after user completes signup
  def init_app_after_first_sign_up
    @user.is_app_init = true
    @user.last_messages_read = (Time.now - 1.week)
    @user.last_notifications_read = (Time.now - 1.week)

    # Notifier.startup_instructions(current_user).deliver_later
    @user.activity(:create)
  end

end

Web/app/helpers/user_helper.rb
require "scrapper/pdf_scrapper"
module UserHelper

  #delete all the papers that were saved earlier
  def cleanUserProfile(user)
      user.papers.destroy_all
  end

  def scrapeUserProfile(user)
    #Ensuring the folder exists
    pdf_folder = user.get_pdf_folder_path
    FileUtils::rm_rf pdf_folder
    FileUtils::mkdir_p pdf_folder
    txt_folder = user.get_pdf_text_path
    FileUtils::rm_rf txt_folder
    FileUtils::mkdir_p txt_folder

    # Notify the user the job is initiated
    user.activity(:publication_update_begin)

    #Running pdf to txt conversion
    url = user.url
    scrapper = PDFScrapper.new(url, 'personal')
    scrapper.downloadAllPdfs(pdf_folder)
    scrapper.convertPdfToText(pdf_folder, txt_folder)

    Dir.foreach(txt_folder) do |item|
      next if item == '.' or item == '..'
      txt_file = txt_folder + '/' + item
      filepath = pdf_folder + "/" + File.basename(item, File.extname(item)) + ".pdf"
      params = {}
      params[:pdf] = File.open(filepath, 'r')
      params[:path] = txt_file
      paper = Paper.new(params)
      if paper.save
        File.delete(filepath)
        if not user.user_papers.create!({paper_id: paper.id})
          Rails.logger.error("Can not save the user_paper")
        end
      else
        Rails.logger.error("Can not save the paper")
      end
    end

    FileUtils::rm_rf pdf_folder

    #setting the status to true
    user.is_scraped = true
    user.save

    # Notify the user the job is complete
    user.activity(:publication_update_complete)
  end

end

Web/app/views/users/_recaptcha.html.erb
<div id="recaptcha_widget" class="recaptcha_widget">
    <div id="recaptcha_image"></div>
</div>

Web/app/views/users/approved_organizers.erb
<%= header_title 'Approved Organizers' %>

<div id="page-heading">
  <%= page_title 'Approved Organizers' %>
</div>

<div class="clearfix"></div>
<% if @approved_organizers.length == 0 %>
    <%= render 'layouts/application/no_result', body: 'You have no organizer who has been approved.' %>
<% else %>
    <table class="table paircon-table table-condensed table-responsive dataTable">
      <thead>
      <tr role="row">
        <th>User Name</th>
        <th>Email</th>
        <th>User Industry</th>
        <th>User Organization</th>
        <th>Date Approved</th>
      </tr>
      </thead>
      <tbody>
      <% @approved_organizers.each do |organizer| %>
          <tr>
            <td><%= organizer.full_name %></td>
            <td><%= organizer.email %></td>
            <td><%= organizer.industry %></td>
            <td><%= organizer.organization %></td>
            <td><%= organizer.updated_at.strftime(DATEFORMAT) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>


<%= javascript_tag "initializeAdmin(#{@approved_organizers.length})" %>

Web/app/views/users/become_organizer.erb
<%= header_title 'Settings' %>

<%= form_for @user, url: request_organizer_user_path(@user.id), html: {method: 'POST', 
  id: 'organizer_request_form'} do |f| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-user" style="margin-right: 5px;" id="drive-header-icon"></i>
        Become Organizer
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h4 class="font-light" align="center">Do you really want to request Organizer Access?
          </h4>
        </div>
      </div>
    </div>

    <div class="modal-footer" style="margin-top:-5px;">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <% if !is_mobile_device? %>
          <span style="float: left !important; margin-top: 5px;">
            <small>Note: This operation is permanent
              and cannot be
              reversed later.
            </small>
          </span>
          <% end %>
          <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
          <%= f.submit 'Become Organizer', :class => 'btn btn-paircon' %>
        </div>
      </div>
    </div>
<% end %>

<%= javascript_tag 'initializeUserOrganizer()' %>

Web/app/views/users/delete.erb
<script src='https://www.google.com/recaptcha/api.js'></script>
<%= header_title 'Settings' %>

<%= form_for @user, url: delete_account_user_path(@user.id), method: 'DELETE' do |f| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-user" style="margin-right: 5px;"></i>
        Delete Account
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h4 class="font-light" align="center">Do you really want to quit using Paircon? By proceeding, you will lose all data associated with Paircon.
          </h4>

          <div class="form-group" style="margin-top:20px; margin-bottom: 20px;">
            <%= f.password_field :current_password, :value => '', :class => 'form-control', placeholder: 'Enter current password' %>
          </div>
          <div class="form-group" align="center">
            <%= render 'recaptcha' %>
            <%= recaptcha_tags ajax: true, :display => {:theme => 'custom'} %>
          </div>
        </div>
      </div>
    </div>

    <div class="modal-footer" style="margin-top:-5px;">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <% if !is_mobile_device? %>
          <span style="float: left !important; margin-top: 5px;">
            <small>Note: This operation is permanent
              and cannot be
              reversed later.
            </small>
          </span>
          <% end %>
          <% if request.xhr? %>
              <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
          <% end %>
          <%= f.submit 'Delete', :class => 'form-control', :class => 'btn btn-paircon' %>
        </div>
      </div>
    </div>
<% end %>

<%= javascript_tag 'initializeUserDelete()' %>

Web/app/views/users/oauth_callback.erb
<div id="success" style="display: none;"><%= @success %></div>
<div id="message" style="display: none;"><%= @message %></div>
<div id="code" style="display: none;"><%= @code %></div>

Web/app/views/users/password_reset.erb
<%= header_title 'Settings' %>

<script src='https://www.google.com/recaptcha/api.js'></script>

<%= form_for @user, url: update_email_password_user_path(@user.id), html: {method: 'POST', id: 'email_passwd_form'} do |f| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-lock" style="margin-right: 5px;" id="drive-header-icon"></i>
        Change Password
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= label 'current_password', '', 'Current Password' %>
            <%= f.password_field :current_password, class: 'form-control', placeholder: 'Enter current password' %>
          </div>
          <div class="form-group">
            <%= label 'new_password', '', 'New Password' %>
            <%= f.password_field :password, class: 'form-control', placeholder: 'Enter new password' %>
          </div>
          <div class="form-group">
            <%= label 'confirm_password', '', 'Confirm Password' %>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Verify new password' %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group" align="center">
            <%= render 'recaptcha' %>
            <%= recaptcha_tags ajax: true, :display => {:theme => 'custom'} %>
          </div>
        </div>
      </div>
    </div>

    <div class="modal-footer">
      <% if request.xhr? %>
          <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
      <% end %>

      <%= f.submit 'Proceed', class: 'btn btn-paircon' %>
    </div>
<% end %>

<%= javascript_tag 'initializeUserPasswordReset()' %>

Web/app/views/users/pending_organizers.erb
<%= header_title 'Pending Organizers' %>

<div id="page-heading">
  <%= page_title 'Pending Organizers' %>
</div>

<div class="clearfix"></div>
<% if @pending_organizers.length == 0 %>
    <%= render 'layouts/application/no_result', body: 'You have no organizer who is pending approval.' %>
<% else %>
    <table class="table paircon-table table-condensed table-responsive dataTable">
      <thead>
      <tr role="row">
        <th>Name</th>
        <th>Email</th>
        <th>User Industry</th>
        <th>User Organization</th>
        <th>Request Date</th>
        <th width="50px;" class="no-sort"></th>
      </tr>
      </thead>
      <tbody>
      <% @pending_organizers.each do |organizer| %>
          <tr>
            <td><%= organizer.full_name %></td>
            <td><%= organizer.email %></td>
            <td><%= organizer.industry %></td>
            <td><%= organizer.organization %></td>
            <td><%= organizer.created_at.strftime(DATEFORMAT) %></td>
            <td>
              <a id='<%= organizer.id %>' class="organizer-approval pointer-cursor"><i class="fa fa-check"></i> Approve</a>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

<%= javascript_tag "initializeAdmin(#{@pending_organizers.length})" %>

Web/app/views/users/publications.erb
<%= header_title @user.full_name %>

<div id="page-heading">
  <%= page_title @user.full_name %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-2 col-sm-12 col-xs-12 text-center col-md-offset-1">
      <%= image_tag @user.logo.url, class: 'profile-image dropzone static conference-logo' %>
      <h3><%= @user.full_name %></h3>
      <h3><%= @user.organization %></h3>
      <h3><%= @user.industry %></h3>
    </div>
    <div class="col-md-8 col-sm-12 col-xs-12">
      <% if @user.papers.length == 0 %>
          <%= render 'layouts/application/no_result', body: @user.full_name + ' has no papers defined.' %>
      <% else %>
          <!-- To Be Completed (Not Possible Without Paper Information Such as Title / Author etc. -->
      <% end %>
    </div>
  </div>
</div>

Web/app/views/users/show.erb
<%= header_title 'Settings' %>

<div id="page-heading">
  <%= page_title 'Personal Settings' %>
</div>

<div class="container">
  <div class="row">

    <div class="col-md-4 col-sm-12 col-xs-12">
      <div class="text-center">
        <h3 id="name">
          <%= @user.full_name %>
          <%= link_to_modal icon_text('pencil', 'Edit'), edit_user_path(@user.id), :class => 'btn btn-sm btn-borderless btn-inactive ' %>
        </h3>

        <div class="profile-image dropzone logo-image" data-resize="false" data-width="300" data-height="300"
             data-url="<%= save_logo_user_url(current_user) %>" data-image="<%= asset_path(current_user.profile_photo) %>"
             data-removeurl="<%= destroy_logo_user_url(current_user) %>">
          <input class="invisible" id="profile-image-upload" type="file" name="thumb" accept="image/*"/>
        </div>

        <div>
          <button id="upload_image_btn" style="margin-top: 20px; margin-bottom: 20px;" class="btn btn-paircon btn-label btn-profile btn-padding">
            <i class="fa fa-upload"></i> Upload Image
          </button>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-sm-12 col-xs-12 ">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <h3>Personal Information</h3>
      </div>
      <table class="table table-responsive pull-left">
        <tbody>
        <tr>
          <td class="profile-title table-accountinfo">Email Address:</td>
          <td class="table-accountinfo"><a href="<%= user_path(@user) %>"><%= @user.email %></a>
          </td>
        </tr>
        <tr>
          <td class="profile-title table-accountinfo">Phone Number:</td>
          <td class="table-accountinfo"><%= @user.phone_number.blank? ? 'N/A' : @user.phone_number %></td>
        </tr>
        <tr>
          <td class="profile-title table-accountinfo">Gender:</td>
          <td class="table-accountinfo"><%= @user.gender == 1 ? 'Male' : 'Female' %></td>
        </tr>
        <tr>
          <td class="profile-title table-accountinfo">Publication URL:
            <% class_name = 'refresh_publication_disabled left-buffer publication_button' %>
            <% spin = false %>
            <% if @user.is_scraped %> <!-- If no scraping job is running -->
                <% type = 'scraped' %>
                <% class_name = 'refresh_publication left-buffer publication_button' %>
            <% elsif @user.url.blank? %> <!-- If user has no URL (disable) -->
                <% type = 'no-url' %>
            <% else %>
                <% type = 'running' %>
                <% spin = true %>
            <% end %>

            <span class="tooltip-wrapper text-center">
              <a class="<%= class_name %>" data-type="<%= type %>">
                <i class="fa fa-refresh fa-lg <%= 'fa-spin' if spin %>" aria-hidden="true"></i>
              </a>
            </span>

          </td>
          <td class="table-accountinfo" style="vertical-align: middle;"><%= @user.url.blank? ? 'N/A' : @user.url %>
          </td>
        </tr>
        <tr>
          <td class="profile-title table-accountinfo">Organization:</td>
          <td class="table-accountinfo"><%= @user.organization %></td>
        </tr>
        <tr>
          <td class="profile-title table-accountinfo">Industry:</td>
          <td class="table-accountinfo"><%= @user.industry %></td>
        </tr>
        <tr>
          <td class="profile-title table-accountinfo">Graduation Year:</td>
          <td class="table-accountinfo"><%= @user.grad_year %></td>
        </tr>
        <tr>
          <td class="profile-title table-accountinfo">User Type:</td>
          <td class="table-accountinfo">
            <% if @user.attendee? and !@user.pending_organizer %>
                <div>Basic User <%= link_to_modal '(Become an Organizer)', become_organizer_user_path(@user.id) %></div>
            <% elsif @user.attendee? and @user.pending_organizer %>
                <div style="opacity: 0.8">Your Organizer Request is Pending</div>
            <% elsif @user.organizer? %>
                Organizer
            <% elsif @user.admin? %>
                Admin
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>

  </div>
  <div class="container">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <h3>Preferences</h3>
    </div>
    <div class="col-md-3 col-sm-12 col-xs-12">
      <%= link_to_modal 'Delete Account', delete_user_path(current_user) %>
    </div>
    <div class="col-md-3 col-sm-12 col-xs-12">
      <%= link_to_modal 'Change Password', password_reset_user_path(current_user) %>
    </div>
  </div>
</div>


<%= javascript_tag "initializeUserShow(#{@user.gender.to_i})" %>
<%= javascript_tag "refreshProfileUrl('" + current_user.id.to_s + "')" %>