Web/config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get '*path' => redirect { |_, request|
    "https://#{request.host_with_port.sub(/^www\./, '')}#{request.fullpath}" },
      constraints: lambda { |request| request.subdomain =~ /^www\./i }

  #root to: redirect { |_, request| PairconConfig.root_domain },
  #     constraints: lambda { |request|
  #       request.subdomain =~ /^www$/i && request.query_parameters.blank?
  #     }

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout'}, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :dashboard
    end

    unauthenticated do
      root 'users/sessions#new'
    end

    get '/recover', to: 'devise/passwords#new'
    post 'user_session', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'

  end

  match '/404', :to => 'errors#not_found', :via => :all
  match '/403', :to => 'errors#unauthorized_access', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all

  mount PdfjsViewer::Rails::Engine => "/pdf", as: 'pdf'

  resources :posts do
    member do
      get :delete
    end
  end

  resources :schedules do
    collection do
      get :get_sessions
      get :get_resources
      get :get_events
      get :get_events_user
      get :delete_resource
      get :new_resource
      get :new_event
      get :delete_event
      get :edit_event

      post :create_resource
      post :create_event
      post :create_resource
      post :create_event
      post :update_event

      delete :destroy_event
      delete :destroy_resource
    end
  end

  resources :papers do
    member do
     get :delete
     delete :destroy
    end
  end

  resources :conferences do
    member do
      get :bulk_upload
      get :invite
      get :delete
      get :user_recommendations

      post :create_invites
      post :destroy_cover
      post :destroy_logo
      post :save_cover
      post :save_logo
      post :attend_conference
      post :process_bulk_upload

      get :home
      get :about_panel
      get :recommendations
      get :posts
      get :schedule
      get :papers
    end
  end

  resources :notifications do
    collection do
      post :read_notification
    end
  end

  resources :home, path: '' do
    collection do
      get :terms
      get :privacy_policy
      get :search
    end
  end

  resources :users, except: [:index] do
    member do
      get :delete
      get :change_active_status
      get :password_reset
      get :timezone
      get :become_organizer
      get :refresh_profile
      get :approved_organizers
      get :pending_organizers
      get :publications

      delete :delete_account

      post :update_email_password
      post :save_logo
      post :destroy_logo
      post :submit_url
      post :request_organizer
      post :approve_organizer
      post :refresh_profile
    end

    collection do
      get :validation
    end
  end

  get '/user/:action/(:id)', controller: 'users'
  get '/auth/failure' => 'application#auth_failure', as: :auth_failure
  get '*path' => 'application#not_found', as: :not_found

end

Web/app/controllers/schedules_controller.rb
# Controller primarily responsible for handling Schedules
class SchedulesController < ApplicationController

  require 'digest/md5'

  before_action :authenticate_user!, except: [:get_resources, :get_events]
  before_action :find_resource, only: [:delete_resource, :destroy_resource]
  before_action :find_event, only: [:delete_event, :destroy_event, :update_event]

  # Action for showing modal for new resource creation
  # @return [HTML] Renders New Resource Modal
  def new_resource
    @conference = Conference.find(params[:conference_id])
    if params[:view] == ConferenceResource::TYPE[:event]
      @title = 'Add Event'
      @body = 'Please enter information about the Event you are hosting and add the name of the Room to which this Event belongs.'
      @rooms = [['Other', 'Other']] + @conference.conference_resources.select(:room).distinct().map { |obj| [obj.room, obj.room] }
    else
      @title = 'Add Session'
      @body = 'Please information about the Session along with the type of Session, name of Paper and the Event to which this Session belongs.'
      @events = @conference.conference_resources.select(:title, :conference_resource_id).distinct().where({:parent_id => nil}).map { |obj| [obj.title, obj.conference_resource_id] }
      papers = @conference.papers.select(:title, :paper_id).order(:title)
      @papers = papers.map { |obj| [obj.title, obj.id] }
    end
    render layout: false
  end

  # Action for processing resource creation
  # @return [HTML] Redirects Back to Previous Location
  def create_resource
    conference_resource_params = params.require(:resource).permit!
    if conference_resource_params[:room] == 'Other'
      room_name = conference_resource_params[:room_other]
    elsif conference_resource_params[:room] == 'None'
      room_name = ''
    else
      room_name = conference_resource_params[:room]
    end

    if params[:view] == ConferenceResource::TYPE[:event]
      event_start_date = DateTime.parse(conference_resource_params[:date] + ' ' + conference_resource_params[:start_time])
      event_end_date = DateTime.parse(conference_resource_params[:date] + ' ' + conference_resource_params[:end_time])

      event_resource = ConferenceResource.create!(
          conference_id: params[:conference_id],
          title: conference_resource_params[:title],
          parent_id: nil,
          room: room_name,
          eventColor: '#' + Digest::MD5.hexdigest(conference_resource_params[:title])[0..5]
      )
      #create the corresponding event for the event_resource
      ConferenceEvent.create!(
          conference_id: params[:conference_id],
          conference_resource_id: event_resource.id,
          title: conference_resource_params[:title],
          start_date: event_start_date,
          end_date: event_end_date,
          color: '#' + Digest::MD5.hexdigest(conference_resource_params[:title])[0..5]
      )
      flash[:notice] = "You have successfully created '#{conference_resource_params[:title]}' Event."
    else
      event_date = ConferenceEvent.find_by_conference_resource_id(conference_resource_params[:parent_id]).start_date.to_date
      session_start_date = DateTime.parse(event_date.to_s + ' ' + conference_resource_params[:start_time])
      session_end_date = DateTime.parse(event_date.to_s + ' ' + conference_resource_params[:end_time])

      session_resource = ConferenceResource.create!(
          conference_id: params[:conference_id],
          title: conference_resource_params[:title],
          parent_id: conference_resource_params[:parent_id],
          room: nil,
          eventColor: '#' + Digest::MD5.hexdigest(conference_resource_params[:title])[0..5]
      )

      ConferenceEvent.create!(
          conference_id: params[:conference_id],
          conference_resource_id: session_resource.id,
          title: conference_resource_params[:title],
          start_date: session_start_date,
          end_date: session_end_date,
          presenter: conference_resource_params[:presenter],
          event_type: conference_resource_params[:event_type].to_i,
          paper_id: conference_resource_params[:paper_id],
          color: '#' + Digest::MD5.hexdigest(conference_resource_params[:title])[0..5]
      )
      flash[:notice] = "You have successfully created '#{conference_resource_params[:title]}' Session."
    end

    redirect_back(fallback_location: root_path)
  end

  # def new_event
  #   @conference = Conference.find(params[:conference_id])
  #
  #   events = @conference.conference_resources.where(parent_id: nil).select(:title, :id).distinct().order(:title)
  #   @events = events.map { |obj| [obj.title, obj.id] }
  #   papers = @conference.papers.select(:title, :id).order(:title)
  #
  #   @papers = papers.map{|obj| [obj.title, obj.id]}
  #   @sessions = [['No Session', 'No Session']]
  #   unless @events.blank?
  #     @sessions = @sessions + @conference.conference_resources.where(parent_id: events.first.id).select(:title, :id).distinct().order(:title).map { |obj| [obj.title, obj.id] }
  #   end
  #
  #   @start_date = params[:start_date].blank? ? '' : DateTime.parse(params[:start_date]).strftime(DATETIMEFORMAT)
  #   @end_date = params[:end_date].blank? ? '' : DateTime.parse(params[:end_date]).strftime(DATETIMEFORMAT)
  #
  #   if !params[:resource_id].blank?
  #     resource = ConferenceResource.find(params[:resource_id])
  #     if resource.parent_id.nil? or resource.parent_id.blank?
  #       @session_name = 'None'
  #       @event_name = resource.title
  #     else
  #       @session_name = resource.title
  #       @event_name = ConferenceResource.find(resource.parent_id).title
  #     end
  #   else
  #     @event_name = ''
  #     @session_name = ''
  #   end
  #
  #   render layout: false
  # end
  #
  # def create_event
  #   conference_event_params = params.require(:event).permit!
  #
  #   if !conference_event_params[:resource_session].blank? and conference_event_params[:resource_session] != 'No session'
  #     resource_id = conference_event_params[:resource_session]
  #   else
  #     resource_id = conference_event_params[:resource_event]
  #   end
  #
  #   ConferenceEvent.create!(
  #       conference_id: params[:conference_id],
  #       conference_resource_id: resource_id,
  #       title: conference_event_params[:title],
  #       start_date: conference_event_params[:start_date],
  #       end_date: conference_event_params[:end_date],
  #       presenter: conference_event_params[:presenter],
  #       event_type: ConferenceEvent.event_types[conference_event_params[:event_type]],
  #       paper_id: conference_event_params[:paper_id],
  #       color: '#' + Digest::MD5.hexdigest(conference_event_params[:title])[0..5]
  #   )
  #
  #   flash[:notice] = "You have successfully created '#{conference_event_params[:title]}' Event."
  #
  #   redirect_back(fallback_location: root_path)
  # end
  #
  # def edit_event
  #   @conference_event = ConferenceEvent.find(params[:id])
  #   @conference = @conference_event.conference
  #   events = @conference.conference_resources.where(parent_id: nil).select(:title, :id).distinct().order(:title)
  #   @events = events.map { |obj| [obj.title, obj.id] }
  #   @sessions = [['No Session', 'No Session']]
  #   unless @events.blank?
  #     @sessions = @sessions + @conference.conference_resources.where(parent_id: events.first.id).select(:title, :id).distinct().order(:title).map { |obj| [obj.title, obj.id] }
  #   end
  #
  #   conference_resource = @conference_event.conference_resource
  #   if (conference_resource.parent_id.nil?)
  #     @session_name = 'None'
  #     @event_name = conference_resource.title
  #   else
  #     @session_name = conference_resource.title
  #     @event_name = ConferenceResource.where(id: conference_resource.parent_id).title
  #   end
  #
  #   render layout: false
  # end
  #
  # def update_event
  #   conference_event_params = params.require(:event).permit!
  #   unless params[:update_dates].blank?
  #     attributes = {start_date: conference_event_params[:start_date],
  #                   end_date: conference_event_params[:end_date],
  #                   conference_resource_id: conference_event_params[:resource_id]}
  #   else
  #     if !conference_event_params[:resource_session].blank? and conference_event_params[:resource_session] != 'No session'
  #       resource_id = conference_event_params[:resource_session]
  #     else
  #       resource_id = conference_event_params[:resource_event]
  #     end
  #
  #     attributes = {conference_resource_id: resource_id,
  #                   title: conference_event_params[:title],
  #                   start_date: conference_event_params[:start_date],
  #                   end_date: conference_event_params[:end_date],
  #                   presenter: conference_event_params[:presenter],
  #                   event_type: ConferenceEvent.event_types[conference_event_params[:event_type]],
  #                   paper_id: conference_event_params[:paper_id],
  #                   color: '#' + Digest::MD5.hexdigest(conference_event_params[:title])[0..5]}
  #   end
  #
  #   if @event.update!(attributes)
  #     flash[:notice] = "You have successfully updated '#{@event.title}'."
  #     status = :success
  #   else
  #     flash[:error] = "There was an error updating '#{@event.title}'. Please try again later"
  #     status = :error
  #   end
  #
  #   unless params[:update_dates].blank?
  #     render json: {status: status, text: @event.title.nil? ? 'Event' : @event.title}
  #   else
  #     redirect_back(fallback_location: root_path)
  #   end
  #
  # end

  # def delete_event
  #   render layout: false
  # end

  # Action for showing resource deletion modal
  # @return [HTML] Renders Delete Resource Modal
  def delete_resource
    render layout: false
  end

  # Action for processing and destroying ConferenceResource object
  # @return [HTML] Redirects to Last Location
  def destroy_resource
    ConferenceResource.transaction do

Web/app/views/schedules/delete_event.erb
<%= header_title 'Delete' %>

<%= form_for @event, url: destroy_event_schedules_path(), method: :delete do |f| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-trash" style="margin-right: 5px;"></i>
        Delete '<%= @event.title %>'
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h4 class="font-light" align="center">Are you sure you want to delete '<%= @event.title %>'?
          </h4>
        </div>
      </div>
    </div>

    <div class="modal-footer" style="margin-top:-5px;">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <% if !is_mobile_device? %>
          <span style="float: left !important; margin-top: 5px;">
            <small>Note: This operation is permanent
              and cannot be
              reversed later.
            </small>
          </span>
          <% end %>
          <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
          <%= f.submit 'Delete', :class => 'btn btn-paircon' %>
        </div>
      </div>
    </div>
<% end %>

Web/app/views/schedules/delete_resource.erb
<%= header_title 'Delete' %>

<%= form_for @resource, url: destroy_resource_schedules_path(), method: :delete do |f| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-trash" style="margin-right: 5px;"></i>
        Delete '<%= @resource.title %>'
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h4 class="font-light" align="center">Are you sure you want to delete '<%= @resource.title %>'?
          </h4>
        </div>
      </div>
    </div>

    <div class="modal-footer" style="margin-top:-5px;">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <% if !is_mobile_device? %>
          <span style="float: left !important; margin-top: 5px;">
            <small>Note: This operation is permanent
              and cannot be
              reversed later.
            </small>
          </span>
          <% end %>
          <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
          <%= f.submit 'Delete', :class => 'btn btn-paircon' %>
        </div>
      </div>
    </div>
<% end %>

Web/app/views/schedules/edit_event.erb
<%= header_title 'Edit Event' %>

<%= form_for :event, url: update_event_schedules_path(), html: {method: :post, id: 'event_form'} do |f| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-calendar" style="margin-right: 5px;"></i>
        Edit Event
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h4 class="font-light" align="center">Fill in the following options to create an Event. Defining a Session is
            optional and will create the Session for that specific Room.
          </h4>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :title, 'Event Name (*)' %>
            <%= f.text_field :title, placeholder: 'Event Name', class: 'form-control', value: @conference_event.title %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :resource_event, 'Event Name (*)' %>
            <%= f.select :resource_event, @events, {}, id: 'event_depend', value: @event_name %>

            <%= f.label :resource_session, 'Session Name' %>
            <%= f.select :resource_session, @sessions, {}, id: 'session_depend', value: @session_name %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :start_date, 'Start Date and Time (*)' %>
            <div class="input-prepend input-group">
              <span class="add-on input-group-addon"><i class="fa fa-calendar"></i></span>
              <%= f.text_field :start_date, placeholder: 'Start Date and Time', id: 'start_date_datepicker', class: 'datetime form-control', value: @conference_event.start_date_str %>
            </div>

          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :end_date, 'End Date and Time (*)' %>
            <div class="input-prepend input-group">
              <span class="add-on input-group-addon"><i class="fa fa-calendar"></i></span>
              <%= f.text_field :end_date, placeholder: 'End Date and Time', class: 'datetime form-control', value: @conference_event.end_date_str %>
            </div>
          </div>
        </div>
      </div>

    </div>

    <div class="modal-footer" style="margin-top:-5px;">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <% if !is_mobile_device? %>
                <span style="float: left !important; margin-top: 5px;">
                  <small>Note: (*) This is a required field.
                  </small>
                </span>
          <% end %>
          <%= link_to_modal 'Delete', delete_event_schedules_path(id: @conference_event.id), style: 'margin-right: 10px;' %>

          <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
          <%= f.submit 'Edit', :class => 'btn btn-paircon' %>
        </div>
      </div>
    </div>
<% end %>

<%= javascript_tag "initializeAddScheduleEvent('" + @conference.start_date_str + "', '" + @conference.end_date_str + "')" %>

Web/app/views/schedules/get_resource.erb
<%= header_title @title %>

<%= form_for :resource, url: create_resource_schedules_path(conference_id: params[:conference_id], view: params[:view]), html: {method: :post, id: 'add_resource_form'} do |f| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-group" style="margin-right: 5px;"></i>
        <%= @title %>
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h4 class="font-light" align="center"><%= @body %>
          </h4>
        </div>
      </div>

      <% if params[:view] == ConferenceResource::TYPE[:auditorium] %>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="form-group">
                <%= f.label :title, 'Auditorium Name (*)' %>
                <%= f.text_field :title, placeholder: 'Name of Auditorium', class: 'form-control' %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="form-group">
                <%= f.label :building, 'Building Name' %>
                <%= f.select :building, @buildings, {}, id: 'conference_build_select' %>
                <%= f.text_field :building_other, placeholder: 'Name of Building', 'data-depends-on': '#conference_build_select', 'data-depends-on-value': 'Other', class: 'form-control', id: 'conference_build_text' %>
              </div>
            </div>
          </div>
      <% else %>
          <% if @auditoriums.blank? %>
              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <h4 class="font-light" align="center">
                    <strong>Please create an Auditorium before adding a room.</strong>
                  </h4>
                </div>
              </div>

          <% else %>
              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <%= f.label :title, 'Room Name (*)' %>
                    <%= f.text_field :title, placeholder: 'Name of Room', class: 'form-control' %>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <%= f.label :parent_id, 'Auditorium Name (*)' %>
                    <%= f.select :parent_id, @auditoriums, {}, id: 'conference_build_select' %>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>

    <div class="modal-footer" style="margin-top:-5px;">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <% unless params[:view] == ConferenceResource::TYPE[:room] and @auditoriums.blank? %>
              <% if !is_mobile_device? %>
                <span style="float: left !important; margin-top: 5px;">
                  <small>Note: (*) This is a required field.
                  </small>
                </span>
              <% end %>
              <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
              <%= f.submit 'Create', :class => 'btn btn-paircon' %>
          <% else %>
              <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

<%= javascript_tag 'initializeAddScheduleResource()' %>

Web/app/views/schedules/new_event.erb
<%= header_title 'Add Event' %>

<%= form_for :event, url: create_event_schedules_path(conference_id: params[:conference_id]), html: {method: :post, id: 'event_form'} do |f| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-calendar" style="margin-right: 5px;"></i>
        Add Event
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h4 class="font-light" align="center">Fill in the following options to create an Event. Defining a Room is
            optional and will create the event for that specific Room.
          </h4>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :title, 'Event Name (*)' %>
            <%= f.text_field :title, placeholder: 'Event Name', class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :resource_event, 'Event Name (*)' %>
            <%= f.select :resource_event, @events, {}, id: 'event_depend', value: @event_name %>

            <%= f.label :resource_session, 'Session Name' %>
            <%= f.select :resource_session, @sessions, {}, id: 'session_depend', value: @session_name %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :start_date, 'Start Date and Time (*)' %>
            <div class="input-prepend input-group">
              <span class="add-on input-group-addon"><i class="fa fa-calendar"></i></span>
              <%= f.text_field :start_date, placeholder: 'Start Date and Time', id: 'start_date_datepicker', class: 'datetime form-control', value: @start_date %>
            </div>

          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :end_date, 'End Date and Time (*)' %>
            <div class="input-prepend input-group">
              <span class="add-on input-group-addon"><i class="fa fa-calendar"></i></span>
              <%= f.text_field :end_date, placeholder: 'End Date and Time', class: 'datetime form-control', value: @end_date %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :presenter, 'Presenter Name (*)' %>
            <%= f.text_field :presenter, placeholder: 'Presenter Name', class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <%= f.label :event_type, 'Event type (*)' %>
            <%=  f.select :event_type, ConferenceEvent.event_types.map { |k, v| [k.humanize, v] } %>
          </div>
        </div>
      </div>

      <% if @papers.blank? %>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <h4 class="font-light" align="center">
                <strong>Please add a Paper before adding an event.</strong>
              </h4>
            </div>
          </div>

      <% else %>

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="form-group">
                <%= f.label :Paper, 'Paper (*)' %>
                <%= f.select :paper_id, @papers, {}, id: 'conference_paper_select', class: 'select' %>
              </div>
            </div>
          </div>
      <% end %>


    </div>

    <div class="modal-footer" style="margin-top:-5px;">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <% if !is_mobile_device? %>
                <span style="float: left !important; margin-top: 5px;">
                  <small>Note: (*) This is a required field.
                  </small>
                </span>
          <% end %>
          <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
          <%= f.submit 'Create', :class => 'btn btn-paircon' %>
        </div>
      </div>
    </div>
<% end %>

<%= javascript_tag "initializeAddScheduleEvent('" + @conference.start_date_str + "', '" + @conference.end_date_str + "')" %>

Web/app/views/schedules/new_resource.erb
<%= header_title @title %>

<%= form_for :resource, url: create_resource_schedules_path(conference_id: params[:conference_id], view: params[:view]), html: {method: :post, id: 'add_resource_form'} do |form| %>
    <div class="modal-header">
      <h1 class="modal-title" id="myModalLabel">
        <i class="fa fa-group" style="margin-right: 5px;"></i>
        <%= @title %>
      </h1>
    </div>

    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h4 class="font-light" align="center"><%= @body %>
          </h4>
        </div>
      </div>

      <% if params[:view] == ConferenceResource::TYPE[:event] %>
          <%= render 'resource_event', form: form %>
      <% else %>
          <% if @events.blank? %>
              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <h4 class="font-light" align="center">
                    <strong>Please create an Event before adding a session.</strong>
                  </h4>
                </div>
              </div>
          <% else %>
              <%= render 'resource_session', form: form %>
          <% end %>
      <% end %>
    </div>

    <div class="modal-footer" style="margin-top:-5px;">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <% if !is_mobile_device? %>
                <span style="float: left !important; margin-top: 5px;">
                  <small>Note: (*) This is a required field.
                  </small>
                </span>
          <% end %>
          <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
          <%= form.submit @title, :class => "btn btn-paircon #{'disabled' if (params[:view] == ConferenceResource::TYPE[:session] and (@events.blank? or @papers.blank?))}" %>
        </div>
      </div>
    </div>
<% end %>

<%= javascript_tag "initializeAddScheduleResource('" + @conference.start_date_str + "', '" + @conference.end_date_str + "')" %>